### ISSUE TITLE
能否DC助手中增加自动重启容器功能

### ISSUE THREAD

**Issue by dongjiqiang** [gxterry/MoviePilot-Plugins#1]
大佬, 能否能否DC助手中增加自动重启容器功能, 按照cron配置自动重启, 感谢
其他大佬的d[]ocker自定义任务]不好使啊, 保存不了

**Comment by gxterry** [comment]
理论上是可以的因为DC支持，但是需要对每个docker配置cron会出现大量cron任务
V2版本再说吧
